[mypy]
python_version = 3.12
strict_optional = True
warn_return_any = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
exclude = (^tests/)|(^migrations/)
ignore_missing_imports = True

[mypy-app.*]
disallow_untyped_defs = False
ignore_errors = True

[mypy-app.integrations.pindora_lock.client]
disallow_untyped_defs = True
ignore_errors = False

[mypy-app.integrations.pindora_lock.service]
disallow_untyped_defs = True
ignore_errors = False
