"""add superadmin 2fa fields

Revision ID: 08ce29e80519
Revises: 60a010dbbc3d
Create Date: 2026-04-24 16:14:37.475990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08ce29e80519'
down_revision = '60a010dbbc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false'))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_2fa_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
