"""Initial PMS models

Revision ID: a0b7abd18461
Revises: e8f2a4b6c9d3
Create Date: 2026-04-26 14:56:35.238961

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a0b7abd18461'
down_revision = 'e8f2a4b6c9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_organization_id'), ['organization_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_property_id'), ['property_id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_unit_id'), ['unit_id'], unique=False)

    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('backups_filename_key'), type_='unique')

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('email_templates_key_key'), type_='unique')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('settings_key_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('settings_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('email_templates_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('backups_filename_key'), ['filename'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_unit_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_guest_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_property_id'))

    op.drop_table('units')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_organization_id'))

    op.drop_table('properties')
    # ### end Alembic commands ###
